// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZWE0-pt2Z3u3wwi0zriVqWn9vdNivqOE',
    appId: '1:925638246861:web:d1a723cd20a37260e28484',
    messagingSenderId: '925638246861',
    projectId: 'cafeteria-project-e8c4c',
    authDomain: 'cafeteria-project-e8c4c.firebaseapp.com',
    storageBucket: 'cafeteria-project-e8c4c.appspot.com',
    measurementId: 'G-1K1BNK7Q5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJfUZG_aSCfyxUb-uSdcHDZx7Ir2pr2rE',
    appId: '1:925638246861:android:fb387f8191a8ee28e28484',
    messagingSenderId: '925638246861',
    projectId: 'cafeteria-project-e8c4c',
    storageBucket: 'cafeteria-project-e8c4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAef1H0U2axgbln9gzQ5buxyMvm9epXNGA',
    appId: '1:925638246861:ios:2161f663cdd18012e28484',
    messagingSenderId: '925638246861',
    projectId: 'cafeteria-project-e8c4c',
    storageBucket: 'cafeteria-project-e8c4c.appspot.com',
    iosClientId: '925638246861-bnoq5q3m24eovvm18agu3vrld506d02n.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeteria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAef1H0U2axgbln9gzQ5buxyMvm9epXNGA',
    appId: '1:925638246861:ios:2161f663cdd18012e28484',
    messagingSenderId: '925638246861',
    projectId: 'cafeteria-project-e8c4c',
    storageBucket: 'cafeteria-project-e8c4c.appspot.com',
    iosClientId: '925638246861-bnoq5q3m24eovvm18agu3vrld506d02n.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeteria',
  );
}
